import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// import localFont from "next/font/local";
// const Switzer = localFont({
//     src: "../../public/fonts/WEB/fonts/Switzer-Regular.woff2",
//     display: "swap",
//     variable: "--font-switzer",
// });
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
